### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by MimiLevy** [MimiLevy/SnakesAndLadders#2]

**Comment by MimiLevy** [comment]
Hi,
[Here](https://app.moqups.com/fm6u3dr065n74zjjOFI4Ql21qeAstQPr/view?ui=0) is a link to my wireframe 



![Image](https://user-images.githubusercontent.com/86372014/221437084-e471b4a0-2403-4e99-a18c-4ec869ad8d65.PNG)

**Comment by AshiraFriedman** [comment]
Super! Looks great!
100%
